# Set VCPKG compiler to clang and C++23

set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(CMAKE_C_COMPILER "clang")
set(CMAKE_CXX_COMPILER "clang++")

set(SPDLOG_DISABLE_DEFAULT_LOGGER ON)
set(SPDLOG_USE_STD_FORMAT ON)
set(SPDLOG_FMT_EXTERNAL OFF)
set(SPDLOG_NO_ATOMIC_LEVELS ON)
set(SPDLOG_NO_TLS ON)
set(SPDLOG_BUILD_PIC ON)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_ITERATOR_DEBUG_LEVEL=0")